package frc.robot.subsystems;

import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.ModuleConfig;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.util.PathPlannerLogging;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Pose3d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Twist2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructArrayPublisher;
import edu.wpi.first.networktables.StructPublisher;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.button.Trigger;
import frc.robot.Constants;
import frc.robot.commands.DriveToPose;
import frc.robot.generated.TunerConstants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.util.RobotState;
import java.util.Optional;
import java.util.function.Supplier;
import org.littletonrobotics.junction.Logger;
import org.photonvision.EstimatedRobotPose;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements Subsystem so it can easily
 * be used in command-based projects.
 *
 * <p>Base: the 2026 Tuner X Swerve Project Generator output as used by FRC 1360 (Rebuilt2026
 * CommandSwerveDrivetrain) WITH PathPlanner / AutoBuilder ({@link #configureAutoBuilder()}, RobotConfig built
 * programmatically — there is no deploy/pathplanner/settings.json) and minus SysId (WPILib's SysIdRoutine
 * starts DataLogManager on construction, which would compete with AdvantageKit's WPILOGWriter —
 * A-06 / D-21). Vision localisation is the Rebuilt2026 way: the two {@link RoomCamera}s are
 * constructed INSIDE the drivetrain and {@link #updatePose()} (verbatim Rebuilt2026 loop) fuses
 * every unread PhotonVision result at the end of {@link #periodic()}.
 *
 * <p>SignalLogger is never started here (A-06). AdvantageKit is the only WPILOG writer.
 *
 * <p>Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
  private static final double kSimLoopPeriod = 0.004; // 4 ms
  private Notifier m_simNotifier = null;
  private double m_lastSimTime;

  /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
  private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
  /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
  private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
  /* Keep track if we've ever applied the operator perspective before or not */
  private boolean m_hasAppliedOperatorPerspective = false;

  /**
   * Field-centric facing-angle request: the driver translates while the drivetrain holds a heading
   * (e.g. face a wall tag). Heading PID runs in radians on the odometry thread; tolerance set in the
   * constructor. No center-of-rotation offset (Subzero has no turret).
   */
  public final SwerveRequest.FieldCentricFacingAngle facingAngleRequest =
      new SwerveRequest.FieldCentricFacingAngle()
          .withDriveRequestType(DriveRequestType.OpenLoopVoltage)
          .withHeadingPID(7.0, 0.0, 0.0);

  public final Trigger swerveAtTargetHeading =
      new Trigger(() -> facingAngleRequest.HeadingController.atSetpoint());

  // ───────────────────────────── PathPlanner (Rebuilt2026 configureAutoBuilder lift) ─────────────────────────────

  /** Swerve request applied while following a PathPlanner path (robot-relative speeds + wheel force feedforwards). */
  private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();

  /**
   * PathPlanner translation / rotation PID (feedback on top of the trajectory feedforward). Rebuilt2026 runs 12 / 7
   * at full speed; the tour paths are capped at 0.47 m/s (frc.robot.AutoConstants), so 5 / 5 is plenty and softer.
   */
  private static final PIDConstants kPathTranslationPid = new PIDConstants(5.0, 0.0, 0.0);
  private static final PIDConstants kPathRotationPid = new PIDConstants(5.0, 0.0, 0.0);

  /**
   * Wheel coefficient of friction used by PathPlanner's RobotConfig to bound acceleration. 1.0 is a placeholder
   * (Colson/billet tread on carpet is ≈ 1.0–1.2; on the room's floor it is unknown). Irrelevant at 0.5 m/s²:
   * the friction limit (≈ 9.8 m/s² × COF) is never reached. TODO(hardware) H-20 — orchestrator: move to
   * Constants.DriveConstants next to kRobotMassKg / kRobotMoiKgM2 (this worker does not own Constants.java).
   */
  private static final double kWheelCofPlaceholder = 1.0;

  /** True once {@link AutoBuilder#configure} succeeded (logged as PathPlanner/Configured every loop). */
  private boolean m_autoBuilderConfigured = false;

  /**
   * Live NetworkTables mirrors of the PathPlanner logging callbacks (Rebuilt2026 StructArrayPublisher style) so the
   * active path / target pose are visible in AdvantageScope + Glass even without the AdvantageKit NT4Publisher.
   * The same data goes to Logger.recordOutput("PathPlanner/…") for the .wpilog.
   */
  private final NetworkTable m_ntPathPlanner = NetworkTableInstance.getDefault().getTable("PathPlanner");
  private final StructArrayPublisher<Pose2d> m_ntActivePath =
      m_ntPathPlanner.getStructArrayTopic("ActivePath", Pose2d.struct).publish();
  private final StructPublisher<Pose2d> m_ntTargetPose =
      m_ntPathPlanner.getStructTopic("TargetPose", Pose2d.struct).publish();
  private final StructPublisher<Pose2d> m_ntCurrentPose =
      m_ntPathPlanner.getStructTopic("CurrentPose", Pose2d.struct).publish();

  /** Last active path handed to the logging callback (empty once a path ends → stale paths vanish). */
  private Pose2d[] m_lastActivePath = new Pose2d[0];

  // ───────────────────────────── room cameras (Rebuilt2026 style) ─────────────────────────────

  private final RoomCamera leftCamera =
      new RoomCamera(
          Constants.VisionConstants.kRobotToLeftCamera, Constants.VisionConstants.kLeftCameraName);
  private final RoomCamera rightCamera =
      new RoomCamera(
          Constants.VisionConstants.kRobotToRightCamera, Constants.VisionConstants.kRightCameraName);
  private final RoomCamera[] swerveCameras = {leftCamera, rightCamera};

  /** Vision estimates fused with FINITE std devs since boot (Drive/VisionMeasurementsAccepted). */
  private long m_visionMeasurementsAccepted = 0;
  /** Vision estimates handed over with MAX_VALUE std devs (ambiguity / distance gate) — no-ops. */
  private long m_visionMeasurementsRejected = 0;

  // ───────────────────────────── sim ground truth ─────────────────────────────

  /** Where the sim robot (and the fused pose) starts; also the default sim truth. */
  private static final Pose2d kSimStartPose = new Pose2d(1.0, 1.0, Rotation2d.kZero);

  /**
   * Sim only: ground-truth robot pose fed to each camera's VisionSystemSim. Integrated every loop from
   * the robot-relative chassis speeds (NOT from getState().Pose, which vision corrects — that would
   * make the sim test circular).
   */
  private Pose2d m_simTruthPose = kSimStartPose;

  private double m_lastSimTruthTime = -1.0;

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants, SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, modules);
    configureCommon();
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, odometryUpdateFrequency, modules);
    configureCommon();
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param odometryStandardDeviation The standard deviation for odometry calculation in the form
   *     [x, y, theta]ᵀ, with units in meters and radians
   * @param visionStandardDeviation The standard deviation for vision calculation in the form [x, y,
   *     theta]ᵀ, with units in meters and radians
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      Matrix<N3, N1> odometryStandardDeviation,
      Matrix<N3, N1> visionStandardDeviation,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(
        drivetrainConstants,
        odometryUpdateFrequency,
        odometryStandardDeviation,
        visionStandardDeviation,
        modules);
    configureCommon();
  }

  /** Shared constructor tail: sim thread + sim truth, heading tolerance, RobotState, scheduler registration. */
  private void configureCommon() {
    if (Utils.isSimulation()) {
      startSimThread();
      // Sim starts inside the room with fused pose == truth; RobotContainer / the orchestrator's test
      // may resetPose() elsewhere afterwards to prove vision pulls it back.
      resetPose(kSimStartPose);
      resetSimTruth(kSimStartPose);
    }
    facingAngleRequest.HeadingController.setTolerance(Math.toRadians(3.0));
    facingAngleRequest.HeadingController.enableContinuousInput(-Math.PI, Math.PI);
    // Rebuilt2026 wires this from RobotContainer; doing it here too is idempotent and guarantees the
    // cameras' "Robot Pose Transformed By Robot To Cam" publisher has a real pose from the first loop.
    RobotState.getInstance().setAllSuppliers(this::getPose, this::getChassisSpeeds);
    // Register explicitly so periodic()/simulationPeriodic() (pose fusion + logging) run even before
    // RobotContainer binds a default command. The generated project relies on setDefaultCommand for this.
    register();

    configureAutoBuilder();
    configurePathPlannerLogging();

    // Sim self-test (agents): SUBZERO_SIM_PATH_TEST=1 SUBZERO_SIM_AUTOENABLE=teleop ./gradlew simulateJava -Pheadless
    // → 2 s after enable: truth + odometry are put at (4.5, 2.3, 0°) (the vision-test start), then DriveToPose runs an
    //   on-the-fly PathPlanner path to (4.8, 3.0, 90°) under the AutoConstants caps. Watch Drive/Pose, Drive/Speeds,
    //   PathPlanner/ActivePath (Pose2d[]), PathPlanner/GoalPose, PathPlanner/DriveToPose/* in frc/logs/akit_*.wpilog.
    if (Utils.isSimulation() && System.getenv("SUBZERO_SIM_PATH_TEST") != null) {
      final Pose2d kSimPathStart = new Pose2d(4.5, 2.3, Rotation2d.kZero);
      final Pose2d kSimPathGoal = new Pose2d(4.8, 3.0, Rotation2d.fromDegrees(90.0));
      new Trigger(DriverStation::isEnabled)
          .onTrue(
              Commands.sequence(
                      Commands.waitSeconds(2.0),
                      runOnce(
                          () -> {
                            resetSimTruth(kSimPathStart);
                            resetPose(kSimPathStart);
                          }),
                      Commands.waitSeconds(0.5),
                      DriveToPose.driveToPose(this, kSimPathGoal),
                      // Hold still for a moment so the log shows the settled end pose.
                      applyRequest(() -> m_pathApplyRobotSpeeds.withSpeeds(new ChassisSpeeds())).withTimeout(1.0))
                  .withName("SimPathTest"));
    }
  }

  // ───────────────────────────── PathPlanner AutoBuilder ─────────────────────────────

  /**
   * Rebuilt2026's configureAutoBuilder(), except the {@link RobotConfig} is built here from TunerConstants /
   * Constants.DriveConstants instead of {@code RobotConfig.fromGUISettings()} (no PathPlanner GUI project exists).
   * Paths are followed with robot-relative speeds + wheel force feedforwards; flipping is disabled (a room has no
   * alliances). Failures are reported to the DS and leave {@code PathPlanner/Configured} false — every
   * {@link AutoBuilder#followPath} would then throw, so DriveToPose guards on {@link AutoBuilder#isConfigured()}.
   */
  private void configureAutoBuilder() {
    try {
      final RobotConfig config = buildRobotConfig();
      AutoBuilder.configure(
          this::getPose, // Supplier of current robot pose (fused)
          this::resetPose, // Consumer for seeding pose against auto
          this::getChassisSpeeds, // Supplier of current robot-relative speeds
          // Consumer of ChassisSpeeds and feedforwards to drive the robot
          (speeds, feedforwards) ->
              setControl(
                  m_pathApplyRobotSpeeds
                      .withSpeeds(speeds)
                      .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                      .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())),
          new PPHolonomicDriveController(kPathTranslationPid, kPathRotationPid),
          config,
          () -> false, // room: never flip paths for an alliance
          this // Subsystem for requirements
          );
      m_autoBuilderConfigured = AutoBuilder.isConfigured();
    } catch (Exception ex) {
      m_autoBuilderConfigured = false;
      DriverStation.reportError(
          "Failed to build PathPlanner RobotConfig / configure AutoBuilder: " + ex, ex.getStackTrace());
    }
  }

  /**
   * PathPlanner robot model from the same numbers the drivetrain itself was built with: module locations from the
   * constructed drivetrain, wheel radius / gear ratio / free speed / slip current from TunerConstants.FrontLeft
   * (all four modules are identical), mass + MOI from Constants.DriveConstants (H-20 placeholders).
   */
  private RobotConfig buildRobotConfig() {
    final var module = TunerConstants.FrontLeft; // WheelRadius (m), DriveMotorGearRatio, SpeedAt12Volts (m/s), SlipCurrent (A)
    // 4.73 m/s = Kraken X60 (6000 rpm) / 6.746 × 2π × 0.0508 m — the chassis is MK4i L2 on Kraken X60s. FOC only
    // with a Pro licence (Constants.DriveConstants.kAssumePhoenixPro, H-23); the difference is a few % of torque.
    final DCMotor driveMotor =
        Constants.DriveConstants.kAssumePhoenixPro ? DCMotor.getKrakenX60Foc(1) : DCMotor.getKrakenX60(1);
    final ModuleConfig moduleConfig =
        new ModuleConfig(
            module.WheelRadius,
            module.SpeedAt12Volts,
            kWheelCofPlaceholder,
            driveMotor,
            module.DriveMotorGearRatio,
            module.SlipCurrent,
            1);
    return new RobotConfig(
        Constants.DriveConstants.kRobotMassKg,
        Constants.DriveConstants.kRobotMoiKgM2,
        moduleConfig,
        getModuleLocations()); // FL, FR, BL, BR — the order the modules were passed to the constructor
  }

  /**
   * Every path PathPlanner calculates goes to AdvantageScope two ways: {@code Logger.recordOutput("PathPlanner/…")}
   * (.wpilog + AK NT4Publisher) and plain NetworkTables struct publishers (live even without AK). FollowPathCommand
   * calls the active-path callback with the path poses at initialize() and with an EMPTY list at end(), so a finished
   * or interrupted path disappears instead of lingering.
   */
  private void configurePathPlannerLogging() {
    PathPlannerLogging.setLogActivePathCallback(
        poses -> {
          m_lastActivePath = poses.toArray(new Pose2d[0]);
          Logger.recordOutput("PathPlanner/ActivePath", m_lastActivePath);
          Logger.recordOutput("PathPlanner/ActivePathPoseCount", m_lastActivePath.length);
          m_ntActivePath.set(m_lastActivePath);
        });
    PathPlannerLogging.setLogTargetPoseCallback(
        pose -> {
          Logger.recordOutput("PathPlanner/TargetPose", pose);
          m_ntTargetPose.set(pose);
        });
    PathPlannerLogging.setLogCurrentPoseCallback(
        pose -> {
          Logger.recordOutput("PathPlanner/CurrentPose", pose);
          m_ntCurrentPose.set(pose);
        });
    // Seed the topics so AdvantageScope lists them before the first path runs.
    m_ntActivePath.set(m_lastActivePath);
    Logger.recordOutput("PathPlanner/ActivePath", m_lastActivePath);
  }

  /** True once AutoBuilder.configure succeeded in the constructor (PathPlanner/Configured). */
  public boolean isAutoBuilderConfigured() {
    return m_autoBuilderConfigured;
  }

  // ───────────────────────────── public accessors ─────────────────────────────

  /** Current fused pose estimate (odometry + accepted vision), room coordinates. */
  public Pose2d getPose() {
    return getState().Pose;
  }

  /** Current robot-relative chassis speeds (getState().Speeds). */
  public ChassisSpeeds getChassisSpeeds() {
    return getState().Speeds;
  }

  /** The room cameras this drivetrain fuses (left, right). */
  /** The camera that faces the robot's LEFT (+Y). */
  public RoomCamera getLeftCamera() {
    return leftCamera;
  }

  /** The camera that faces the robot's RIGHT (−Y) — the side the arm extends toward. */
  public RoomCamera getRightCamera() {
    return rightCamera;
  }

  public RoomCamera[] getCameras() {
    return swerveCameras;
  }

  /** Sim only: the ground-truth pose the vision sim sees (== kSimStartPose on the robot). */
  public Pose2d getSimTruthPose() {
    return m_simTruthPose;
  }

  /**
   * Sim only: teleport the ground truth (and every camera's VisionSystemSim history) to {@code pose}.
   * Does NOT touch odometry — pair with {@link #resetPose(Pose2d)} if the fused pose should follow.
   */
  public void resetSimTruth(Pose2d pose) {
    m_simTruthPose = pose;
    m_lastSimTruthTime = -1.0;
    for (RoomCamera cam : swerveCameras) {
      cam.resetSimPose(pose);
    }
  }

  /**
   * Returns a command that applies the specified control request to this swerve drivetrain.
   *
   * @param request Function returning the request to apply
   * @return Command to run
   */
  public Command applyRequest(Supplier<SwerveRequest> request) {
    return run(() -> this.setControl(request.get()));
  }

  // ───────────────────────────── periodic / sim ─────────────────────────────

  @Override
  public void periodic() {
    /*
     * Operator perspective: FORCED to the blue/+X perspective (Constants.DriveConstants.kOperatorPerspective).
     * The generated code derives it from DriverStation.getAlliance(); a DS with no FMS defaults to RED 1, which
     * made "forward" drive toward field −X (the REAR wall of the room layout) and made seedFieldCentric() set the
     * heading to 180° while the robot faced the FRONT wall — a 180° fight with vision. A room has no alliances:
     * joystick forward = field +X = the front wall, always.
     */
    if (!m_hasAppliedOperatorPerspective) {
      setOperatorPerspectiveForward(Constants.DriveConstants.kOperatorPerspective);
      m_hasAppliedOperatorPerspective = true;
    }
    Logger.recordOutput("Drive/OperatorPerspectiveDeg", Constants.DriveConstants.kOperatorPerspective.getDegrees());
    Logger.recordOutput(
        "Drive/DsAlliance", DriverStation.getAlliance().map(Enum::name).orElse("none") + " (ignored)");

    // AdvantageKit lite (D-21): outputs only. Struct types (Pose2d, SwerveModuleState[], ChassisSpeeds) are free.
    final var state = getState();
    Logger.recordOutput("Drive/Pose", state.Pose);
    Logger.recordOutput("Drive/Pose3d", new Pose3d(state.Pose));
    Logger.recordOutput("Drive/ModuleStates", state.ModuleStates);
    Logger.recordOutput("Drive/ModuleTargets", state.ModuleTargets);
    Logger.recordOutput("Drive/Speeds", state.Speeds);
    Logger.recordOutput("Drive/CameraCount", swerveCameras.length);

    this.updatePose();
    Logger.recordOutput("Drive/VisionMeasurementsAccepted", m_visionMeasurementsAccepted);
    Logger.recordOutput("Drive/VisionMeasurementsRejected", m_visionMeasurementsRejected);

    // PathPlanner status (the path / target / current-pose callbacks log on their own when a path is active).
    Logger.recordOutput("PathPlanner/Configured", m_autoBuilderConfigured);
    Logger.recordOutput("PathPlanner/PathActive", m_lastActivePath.length > 0);
  }

  /**
   * Sim only (scheduler calls this after periodic() when RobotBase.isSimulation()). Maintains the
   * SEPARATE ground-truth pose: truth ← truth.exp(robot-relative speeds × dt), then feeds it to each
   * camera's VisionSystemSim. Logs Drive/SimTruthPose and the fused-vs-truth error.
   */
  @Override
  public void simulationPeriodic() {
    final double now = Timer.getFPGATimestamp();
    if (m_lastSimTruthTime >= 0.0) {
      final double dt = MathUtil.clamp(now - m_lastSimTruthTime, 0.0, 0.1);
      final ChassisSpeeds speeds = getState().Speeds; // robot-relative
      m_simTruthPose =
          m_simTruthPose.exp(
              new Twist2d(
                  speeds.vxMetersPerSecond * dt,
                  speeds.vyMetersPerSecond * dt,
                  speeds.omegaRadiansPerSecond * dt));
    }
    m_lastSimTruthTime = now;

    for (RoomCamera cam : swerveCameras) {
      cam.updateSimPose(m_simTruthPose);
    }

    final Pose2d fused = getState().Pose;
    Logger.recordOutput("Drive/SimTruthPose", m_simTruthPose);
    Logger.recordOutput("Drive/SimTruthPose3d", new Pose3d(m_simTruthPose));
    Logger.recordOutput(
        "Drive/SimPoseError_m",
        fused.getTranslation().getDistance(m_simTruthPose.getTranslation()));
    Logger.recordOutput(
        "Drive/SimPoseError_deg",
        Math.abs(fused.getRotation().minus(m_simTruthPose.getRotation()).getDegrees()));
  }

  private void startSimThread() {
    m_lastSimTime = Utils.getCurrentTimeSeconds();

    /* Run simulation at a faster rate so PID gains behave more reasonably */
    m_simNotifier =
        new Notifier(
            () -> {
              final double currentTime = Utils.getCurrentTimeSeconds();
              double deltaTime = currentTime - m_lastSimTime;
              m_lastSimTime = currentTime;

              /* use the measured time delta, get battery voltage from WPILib */
              updateSimState(deltaTime, RobotController.getBatteryVoltage());
            });
    m_simNotifier.startPeriodic(kSimLoopPeriod);
  }

  // ───────────────────────────── vision fusion (Rebuilt2026 updatePose, verbatim) ─────────────────────────────

  private void updatePose() {
    for (RoomCamera orbitCamera : swerveCameras) {
      orbitCamera.updatePipelineResults();
      Optional<EstimatedRobotPose> visionEst = Optional.empty();
      for (var result : orbitCamera.getPipelineResults()) {
        visionEst = orbitCamera.getPhotonPoseEstimator().estimateCoprocMultiTagPose(result);
        if (visionEst.isEmpty()) {
          visionEst = orbitCamera.getPhotonPoseEstimator().estimateLowestAmbiguityPose(result);
        }
        orbitCamera.updateEstimationStdDevs(visionEst, result.getTargets());

        visionEst.ifPresent(
            est -> {
              this.addVisionMeasurement(
                  est.estimatedPose.toPose2d(),
                  est.timestampSeconds,
                  orbitCamera.getEstimationStdDevs());
              if (orbitCamera.isEstimateRejected()) {
                m_visionMeasurementsRejected++;
              } else {
                m_visionMeasurementsAccepted++;
              }
              orbitCamera.updateStructPublisher(est.estimatedPose.toPose2d());
            });
      }
    }
  }

  // ───────────────────────────── vision timestamp plumbing ─────────────────────────────

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
   * while still accounting for measurement noise.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in seconds (FPGA time base).
   */
  @Override
  public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
    super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
  }

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
   * while still accounting for measurement noise.
   *
   * <p>Note that the vision measurement standard deviations passed into this method will continue
   * to apply to future measurements until a subsequent call to {@link
   * #setVisionMeasurementStdDevs(Matrix)} or this method.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in seconds (FPGA time base).
   * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement in the form
   *     [x, y, theta]ᵀ, with units in meters and radians.
   */
  @Override
  public void addVisionMeasurement(
      Pose2d visionRobotPoseMeters, double timestampSeconds, Matrix<N3, N1> visionMeasurementStdDevs) {
    super.addVisionMeasurement(
        visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
  }

  /**
   * Return the pose at a given timestamp, if the buffer is not empty.
   *
   * @param timestampSeconds The timestamp of the pose in seconds (FPGA time base).
   * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
   */
  @Override
  public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
    return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
  }
}
