package frc.robot.subsystems;

import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Pose3d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Twist2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.button.Trigger;
import frc.robot.Constants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.util.RobotState;
import java.util.Optional;
import java.util.function.Supplier;
import org.littletonrobotics.junction.Logger;
import org.photonvision.EstimatedRobotPose;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements Subsystem so it can easily
 * be used in command-based projects.
 *
 * <p>Base: the 2026 Tuner X Swerve Project Generator output as used by FRC 1360 (Rebuilt2026
 * CommandSwerveDrivetrain) minus PathPlanner / AutoBuilder and minus SysId (WPILib's SysIdRoutine
 * starts DataLogManager on construction, which would compete with AdvantageKit's WPILOGWriter —
 * A-06 / D-21). Vision localisation is the Rebuilt2026 way: the two {@link RoomCamera}s are
 * constructed INSIDE the drivetrain and {@link #updatePose()} (verbatim Rebuilt2026 loop) fuses
 * every unread PhotonVision result at the end of {@link #periodic()}.
 *
 * <p>SignalLogger is never started here (A-06). AdvantageKit is the only WPILOG writer.
 *
 * <p>Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
  private static final double kSimLoopPeriod = 0.004; // 4 ms
  private Notifier m_simNotifier = null;
  private double m_lastSimTime;

  /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
  private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
  /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
  private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
  /* Keep track if we've ever applied the operator perspective before or not */
  private boolean m_hasAppliedOperatorPerspective = false;

  /**
   * Field-centric facing-angle request: the driver translates while the drivetrain holds a heading
   * (e.g. face a wall tag). Heading PID runs in radians on the odometry thread; tolerance set in the
   * constructor. No center-of-rotation offset (Subzero has no turret).
   */
  public final SwerveRequest.FieldCentricFacingAngle facingAngleRequest =
      new SwerveRequest.FieldCentricFacingAngle()
          .withDriveRequestType(DriveRequestType.OpenLoopVoltage)
          .withHeadingPID(7.0, 0.0, 0.0);

  public final Trigger swerveAtTargetHeading =
      new Trigger(() -> facingAngleRequest.HeadingController.atSetpoint());

  // ───────────────────────────── room cameras (Rebuilt2026 style) ─────────────────────────────

  private final RoomCamera leftCamera =
      new RoomCamera(
          Constants.VisionConstants.kRobotToLeftCamera, Constants.VisionConstants.kLeftCameraName);
  private final RoomCamera rightCamera =
      new RoomCamera(
          Constants.VisionConstants.kRobotToRightCamera, Constants.VisionConstants.kRightCameraName);
  private final RoomCamera[] swerveCameras = {leftCamera, rightCamera};

  /** Vision estimates fused with FINITE std devs since boot (Drive/VisionMeasurementsAccepted). */
  private long m_visionMeasurementsAccepted = 0;
  /** Vision estimates handed over with MAX_VALUE std devs (ambiguity / distance gate) — no-ops. */
  private long m_visionMeasurementsRejected = 0;

  // ───────────────────────────── sim ground truth ─────────────────────────────

  /** Where the sim robot (and the fused pose) starts; also the default sim truth. */
  private static final Pose2d kSimStartPose = new Pose2d(1.0, 1.0, Rotation2d.kZero);

  /**
   * Sim only: ground-truth robot pose fed to each camera's VisionSystemSim. Integrated every loop from
   * the robot-relative chassis speeds (NOT from getState().Pose, which vision corrects — that would
   * make the sim test circular).
   */
  private Pose2d m_simTruthPose = kSimStartPose;

  private double m_lastSimTruthTime = -1.0;

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants, SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, modules);
    configureCommon();
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, odometryUpdateFrequency, modules);
    configureCommon();
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param odometryStandardDeviation The standard deviation for odometry calculation in the form
   *     [x, y, theta]ᵀ, with units in meters and radians
   * @param visionStandardDeviation The standard deviation for vision calculation in the form [x, y,
   *     theta]ᵀ, with units in meters and radians
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      Matrix<N3, N1> odometryStandardDeviation,
      Matrix<N3, N1> visionStandardDeviation,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(
        drivetrainConstants,
        odometryUpdateFrequency,
        odometryStandardDeviation,
        visionStandardDeviation,
        modules);
    configureCommon();
  }

  /** Shared constructor tail: sim thread + sim truth, heading tolerance, RobotState, scheduler registration. */
  private void configureCommon() {
    if (Utils.isSimulation()) {
      startSimThread();
      // Sim starts inside the room with fused pose == truth; RobotContainer / the orchestrator's test
      // may resetPose() elsewhere afterwards to prove vision pulls it back.
      resetPose(kSimStartPose);
      resetSimTruth(kSimStartPose);
    }
    facingAngleRequest.HeadingController.setTolerance(Math.toRadians(3.0));
    facingAngleRequest.HeadingController.enableContinuousInput(-Math.PI, Math.PI);
    // Rebuilt2026 wires this from RobotContainer; doing it here too is idempotent and guarantees the
    // cameras' "Robot Pose Transformed By Robot To Cam" publisher has a real pose from the first loop.
    RobotState.getInstance().setAllSuppliers(this::getPose, this::getChassisSpeeds);
    // Register explicitly so periodic()/simulationPeriodic() (pose fusion + logging) run even before
    // RobotContainer binds a default command. The generated project relies on setDefaultCommand for this.
    register();
  }

  // ───────────────────────────── public accessors ─────────────────────────────

  /** Current fused pose estimate (odometry + accepted vision), room coordinates. */
  public Pose2d getPose() {
    return getState().Pose;
  }

  /** Current robot-relative chassis speeds (getState().Speeds). */
  public ChassisSpeeds getChassisSpeeds() {
    return getState().Speeds;
  }

  /** The room cameras this drivetrain fuses (left, right). */
  public RoomCamera[] getCameras() {
    return swerveCameras;
  }

  /** Sim only: the ground-truth pose the vision sim sees (== kSimStartPose on the robot). */
  public Pose2d getSimTruthPose() {
    return m_simTruthPose;
  }

  /**
   * Sim only: teleport the ground truth (and every camera's VisionSystemSim history) to {@code pose}.
   * Does NOT touch odometry — pair with {@link #resetPose(Pose2d)} if the fused pose should follow.
   */
  public void resetSimTruth(Pose2d pose) {
    m_simTruthPose = pose;
    m_lastSimTruthTime = -1.0;
    for (RoomCamera cam : swerveCameras) {
      cam.resetSimPose(pose);
    }
  }

  /**
   * Returns a command that applies the specified control request to this swerve drivetrain.
   *
   * @param request Function returning the request to apply
   * @return Command to run
   */
  public Command applyRequest(Supplier<SwerveRequest> request) {
    return run(() -> this.setControl(request.get()));
  }

  // ───────────────────────────── periodic / sim ─────────────────────────────

  @Override
  public void periodic() {
    /*
     * Periodically try to apply the operator perspective.
     * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
     * This allows us to correct the perspective in case the robot code restarts mid-match.
     * Otherwise, only check and apply the operator perspective if the DS is disabled.
     * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
     */
    if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
      DriverStation.getAlliance()
          .ifPresent(
              allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
              });
    }

    // AdvantageKit lite (D-21): outputs only. Struct types (Pose2d, SwerveModuleState[], ChassisSpeeds) are free.
    final var state = getState();
    Logger.recordOutput("Drive/Pose", state.Pose);
    Logger.recordOutput("Drive/Pose3d", new Pose3d(state.Pose));
    Logger.recordOutput("Drive/ModuleStates", state.ModuleStates);
    Logger.recordOutput("Drive/ModuleTargets", state.ModuleTargets);
    Logger.recordOutput("Drive/Speeds", state.Speeds);
    Logger.recordOutput("Drive/CameraCount", swerveCameras.length);

    this.updatePose();
    Logger.recordOutput("Drive/VisionMeasurementsAccepted", m_visionMeasurementsAccepted);
    Logger.recordOutput("Drive/VisionMeasurementsRejected", m_visionMeasurementsRejected);
  }

  /**
   * Sim only (scheduler calls this after periodic() when RobotBase.isSimulation()). Maintains the
   * SEPARATE ground-truth pose: truth ← truth.exp(robot-relative speeds × dt), then feeds it to each
   * camera's VisionSystemSim. Logs Drive/SimTruthPose and the fused-vs-truth error.
   */
  @Override
  public void simulationPeriodic() {
    final double now = Timer.getFPGATimestamp();
    if (m_lastSimTruthTime >= 0.0) {
      final double dt = MathUtil.clamp(now - m_lastSimTruthTime, 0.0, 0.1);
      final ChassisSpeeds speeds = getState().Speeds; // robot-relative
      m_simTruthPose =
          m_simTruthPose.exp(
              new Twist2d(
                  speeds.vxMetersPerSecond * dt,
                  speeds.vyMetersPerSecond * dt,
                  speeds.omegaRadiansPerSecond * dt));
    }
    m_lastSimTruthTime = now;

    for (RoomCamera cam : swerveCameras) {
      cam.updateSimPose(m_simTruthPose);
    }

    final Pose2d fused = getState().Pose;
    Logger.recordOutput("Drive/SimTruthPose", m_simTruthPose);
    Logger.recordOutput("Drive/SimTruthPose3d", new Pose3d(m_simTruthPose));
    Logger.recordOutput(
        "Drive/SimPoseError_m",
        fused.getTranslation().getDistance(m_simTruthPose.getTranslation()));
    Logger.recordOutput(
        "Drive/SimPoseError_deg",
        Math.abs(fused.getRotation().minus(m_simTruthPose.getRotation()).getDegrees()));
  }

  private void startSimThread() {
    m_lastSimTime = Utils.getCurrentTimeSeconds();

    /* Run simulation at a faster rate so PID gains behave more reasonably */
    m_simNotifier =
        new Notifier(
            () -> {
              final double currentTime = Utils.getCurrentTimeSeconds();
              double deltaTime = currentTime - m_lastSimTime;
              m_lastSimTime = currentTime;

              /* use the measured time delta, get battery voltage from WPILib */
              updateSimState(deltaTime, RobotController.getBatteryVoltage());
            });
    m_simNotifier.startPeriodic(kSimLoopPeriod);
  }

  // ───────────────────────────── vision fusion (Rebuilt2026 updatePose, verbatim) ─────────────────────────────

  private void updatePose() {
    for (RoomCamera orbitCamera : swerveCameras) {
      orbitCamera.updatePipelineResults();
      Optional<EstimatedRobotPose> visionEst = Optional.empty();
      for (var result : orbitCamera.getPipelineResults()) {
        visionEst = orbitCamera.getPhotonPoseEstimator().estimateCoprocMultiTagPose(result);
        if (visionEst.isEmpty()) {
          visionEst = orbitCamera.getPhotonPoseEstimator().estimateLowestAmbiguityPose(result);
        }
        orbitCamera.updateEstimationStdDevs(visionEst, result.getTargets());

        visionEst.ifPresent(
            est -> {
              this.addVisionMeasurement(
                  est.estimatedPose.toPose2d(),
                  est.timestampSeconds,
                  orbitCamera.getEstimationStdDevs());
              if (orbitCamera.isEstimateRejected()) {
                m_visionMeasurementsRejected++;
              } else {
                m_visionMeasurementsAccepted++;
              }
              orbitCamera.updateStructPublisher(est.estimatedPose.toPose2d());
            });
      }
    }
  }

  // ───────────────────────────── vision timestamp plumbing ─────────────────────────────

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
   * while still accounting for measurement noise.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in seconds (FPGA time base).
   */
  @Override
  public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
    super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
  }

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
   * while still accounting for measurement noise.
   *
   * <p>Note that the vision measurement standard deviations passed into this method will continue
   * to apply to future measurements until a subsequent call to {@link
   * #setVisionMeasurementStdDevs(Matrix)} or this method.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in seconds (FPGA time base).
   * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement in the form
   *     [x, y, theta]ᵀ, with units in meters and radians.
   */
  @Override
  public void addVisionMeasurement(
      Pose2d visionRobotPoseMeters, double timestampSeconds, Matrix<N3, N1> visionMeasurementStdDevs) {
    super.addVisionMeasurement(
        visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
  }

  /**
   * Return the pose at a given timestamp, if the buffer is not empty.
   *
   * @param timestampSeconds The timestamp of the pose in seconds (FPGA time base).
   * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
   */
  @Override
  public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
    return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
  }
}
