package frc.robot.subsystems;

import static edu.wpi.first.units.Units.Meters;

import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.button.Trigger;
import frc.robot.Constants;
import frc.robot.commands.AlignToTagCommand;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import java.util.List;
import java.util.Optional;
import java.util.function.Supplier;
import org.littletonrobotics.junction.Logger;
import org.photonvision.EstimatedRobotPose;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements Subsystem so it can easily
 * be used in command-based projects.
 *
 * <p>Base: the 2026 Tuner X Swerve Project Generator output (Rebuilt2026 key file) minus PathPlanner /
 * AutoBuilder, minus the OrbitCamera fields, minus SysId (WPILib's SysIdRoutine starts DataLogManager on
 * construction, which would compete with AdvantageKit's WPILOGWriter — A-06 / D-21). Vision fusion is
 * the 2025 SwerveProgrammingChassis {@code updatePose()} intent re-added on top of the frozen
 * {@link RoomCamera} seam (docs/contracts.md §3.1, A-10).
 *
 * <p>SignalLogger is never started here (A-06). AdvantageKit is the only WPILOG writer.
 *
 * <p>Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
  private static final double kSimLoopPeriod = 0.004; // 4 ms
  private Notifier m_simNotifier = null;
  private double m_lastSimTime;

  /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
  private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
  /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
  private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
  /* Keep track if we've ever applied the operator perspective before or not */
  private boolean m_hasAppliedOperatorPerspective = false;

  /** Room cameras fused in {@link #updatePose()}; set once by RobotContainer via {@link #setCameras}. */
  private List<RoomCamera> m_cameras = List.of();

  /** True once any vision estimate has been accepted (the outlier gate is bypassed until then). */
  private boolean m_hasVisionFix = false;

  /**
   * Field-centric facing-angle request: the driver translates while the drivetrain holds a heading
   * (e.g. face a wall tag). Heading PID runs in radians on the odometry thread; tolerance set in the
   * constructor. No center-of-rotation offset (Subzero has no turret).
   */
  public final SwerveRequest.FieldCentricFacingAngle facingAngleRequest =
      new SwerveRequest.FieldCentricFacingAngle()
          .withDriveRequestType(DriveRequestType.OpenLoopVoltage)
          .withHeadingPID(7.0, 0.0, 0.0);

  public final Trigger swerveAtTargetHeading =
      new Trigger(() -> facingAngleRequest.HeadingController.atSetpoint());

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants, SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, modules);
    configureCommon();
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, odometryUpdateFrequency, modules);
    configureCommon();
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param odometryStandardDeviation The standard deviation for odometry calculation in the form
   *     [x, y, theta]ᵀ, with units in meters and radians
   * @param visionStandardDeviation The standard deviation for vision calculation in the form [x, y,
   *     theta]ᵀ, with units in meters and radians
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      Matrix<N3, N1> odometryStandardDeviation,
      Matrix<N3, N1> visionStandardDeviation,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(
        drivetrainConstants,
        odometryUpdateFrequency,
        odometryStandardDeviation,
        visionStandardDeviation,
        modules);
    configureCommon();
  }

  /** Shared constructor tail: sim thread, heading tolerance, scheduler registration. */
  private void configureCommon() {
    if (Utils.isSimulation()) {
      startSimThread();
    }
    facingAngleRequest.HeadingController.setTolerance(Math.toRadians(3.0));
    facingAngleRequest.HeadingController.enableContinuousInput(-Math.PI, Math.PI);
    // Register explicitly so periodic()/simulationPeriodic() (pose fusion + logging) run even before
    // RobotContainer binds a default command. The generated project relies on setDefaultCommand for this.
    register();
  }

  // ───────────────────────────── frozen seam (§3.1) ─────────────────────────────

  /** Cameras to fuse in {@link #updatePose()}. Call once from RobotContainer after construction. */
  public void setCameras(RoomCamera... cams) {
    m_cameras = List.of(cams);
  }

  /** Cameras fused by this drivetrain (empty until {@link #setCameras} is called). */
  public List<RoomCamera> getCameras() {
    return m_cameras;
  }

  /** Current fused pose estimate (odometry + accepted vision), blue-alliance/room coordinates. */
  public Pose2d getPose() {
    return getState().Pose;
  }

  /**
   * Fuse every camera's {@link RoomCamera#update()} into the pose estimator. Called once per loop
   * from {@link #periodic()}. Gate (2025 updatePose intent, re-enabled): an estimate farther than
   * {@link Constants.VisionConstants#kVisionOutlierGate} from the current pose is rejected — unless
   * no vision estimate has ever been accepted, so the first fix can pull odometry onto the room frame.
   */
  public void updatePose() {
    final Pose2d current = getPose();
    final double gateMeters = Constants.VisionConstants.kVisionOutlierGate.in(Meters);
    for (RoomCamera cam : m_cameras) {
      Optional<EstimatedRobotPose> est = cam.update(); // once per loop per camera (seam contract)
      final String key = "Drive/Vision/" + cam.getName();
      if (est.isEmpty()) {
        Logger.recordOutput(key + "/HasEstimate", false);
        continue;
      }
      final Pose2d visionPose = est.get().estimatedPose.toPose2d();
      final double jump = visionPose.getTranslation().getDistance(current.getTranslation());
      final boolean accepted = !m_hasVisionFix || jump <= gateMeters;
      Logger.recordOutput(key + "/HasEstimate", true);
      Logger.recordOutput(key + "/Pose", visionPose);
      Logger.recordOutput(key + "/JumpMeters", jump);
      Logger.recordOutput(key + "/Accepted", accepted);
      if (accepted) {
        // The override below converts the PhotonLib FPGA timestamp with Utils.fpgaToCurrentTime once.
        addVisionMeasurement(visionPose, est.get().timestampSeconds, cam.getEstimationStdDevs());
        m_hasVisionFix = true;
      }
    }
  }

  /**
   * Returns a command that applies the specified control request to this swerve drivetrain.
   *
   * @param request Function returning the request to apply
   * @return Command to run
   */
  public Command applyRequest(Supplier<SwerveRequest> request) {
    return run(() -> this.setControl(request.get()));
  }

  /**
   * Vision-leashed, speed-capped (safety §2/§7) drive to {@code robotToTagOffset} relative to tag
   * {@code tagId}. The command itself (W3) owns the leash, caps, tolerance and the 8 s timeout and
   * exposes {@link AlignToTagCommand#wasRefused()}.
   */
  public Command alignToTag(int tagId, Pose2d robotToTagOffset) {
    return new AlignToTagCommand(this, getCameras(), tagId, robotToTagOffset);
  }

  // ───────────────────────────── periodic / sim ─────────────────────────────

  @Override
  public void periodic() {
    /*
     * Periodically try to apply the operator perspective.
     * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
     * This allows us to correct the perspective in case the robot code restarts mid-match.
     * Otherwise, only check and apply the operator perspective if the DS is disabled.
     * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
     */
    if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
      DriverStation.getAlliance()
          .ifPresent(
              allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
              });
    }

    updatePose();

    // AdvantageKit lite (D-21): outputs only. Struct types (Pose2d, SwerveModuleState[], ChassisSpeeds) are free.
    final var state = getState();
    Logger.recordOutput("Drive/Pose", state.Pose);
    Logger.recordOutput("Drive/ModuleStates", state.ModuleStates);
    Logger.recordOutput("Drive/ModuleTargets", state.ModuleTargets);
    Logger.recordOutput("Drive/Speeds", state.Speeds);
    Logger.recordOutput("Drive/HasVisionFix", m_hasVisionFix);
    Logger.recordOutput("Drive/CameraCount", m_cameras.size());
  }

  /** Main-thread sim hook: feed ground truth to each camera's VisionSystemSim (seam: updateSimPose). */
  @Override
  public void simulationPeriodic() {
    final Pose2d truth = getPose();
    for (RoomCamera cam : m_cameras) {
      cam.updateSimPose(truth);
    }
  }

  private void startSimThread() {
    m_lastSimTime = Utils.getCurrentTimeSeconds();

    /* Run simulation at a faster rate so PID gains behave more reasonably */
    m_simNotifier =
        new Notifier(
            () -> {
              final double currentTime = Utils.getCurrentTimeSeconds();
              double deltaTime = currentTime - m_lastSimTime;
              m_lastSimTime = currentTime;

              /* use the measured time delta, get battery voltage from WPILib */
              updateSimState(deltaTime, RobotController.getBatteryVoltage());
            });
    m_simNotifier.startPeriodic(kSimLoopPeriod);
  }

  // ───────────────────────────── vision timestamp plumbing ─────────────────────────────

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
   * while still accounting for measurement noise.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in seconds (FPGA time base).
   */
  @Override
  public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
    super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
  }

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
   * while still accounting for measurement noise.
   *
   * <p>Note that the vision measurement standard deviations passed into this method will continue
   * to apply to future measurements until a subsequent call to {@link
   * #setVisionMeasurementStdDevs(Matrix)} or this method.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in seconds (FPGA time base).
   * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement in the form
   *     [x, y, theta]ᵀ, with units in meters and radians.
   */
  @Override
  public void addVisionMeasurement(
      Pose2d visionRobotPoseMeters, double timestampSeconds, Matrix<N3, N1> visionMeasurementStdDevs) {
    super.addVisionMeasurement(
        visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
  }

  /**
   * Return the pose at a given timestamp, if the buffer is not empty.
   *
   * @param timestampSeconds The timestamp of the pose in seconds (FPGA time base).
   * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
   */
  @Override
  public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
    return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
  }
}
