/* Generated by Phoenix Tuner X */
/* Config matched EXACTLY to FRC1360/SwerveProgrammingChassis/CTREELEVATOR (commit 0d19dde) — 2026-09-19.
 * Deviations (2026-09-20, incremental control): MotionMagic cruise 12 -> 6.25 rps (= 0.75 m/s) and accel
 * 80 -> 25 rps^2 on the leader; default command holds a persistent TARGET (jogBy +/-1 in) instead of
 * manualDrive(0); kMaxHeight 0 -> 1.0 m (sim/Mechanism2d only); Logger.recordOutput lines in periodic(). */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.function.DoubleSupplier;
import java.util.function.Supplier;

import com.ctre.phoenix6.BaseStatusSignal;
import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.DutyCycleOut;
import com.ctre.phoenix6.controls.Follower;
import com.ctre.phoenix6.controls.MotionMagicVoltage;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.ForwardLimitSourceValue;
import com.ctre.phoenix6.signals.ForwardLimitTypeValue;
import com.ctre.phoenix6.signals.GravityTypeValue;
import com.ctre.phoenix6.signals.MotorAlignmentValue;
import com.ctre.phoenix6.signals.NeutralModeValue;
import com.ctre.phoenix6.signals.ReverseLimitSourceValue;
import com.ctre.phoenix6.signals.ReverseLimitTypeValue;
import com.ctre.phoenix6.sim.ChassisReference;
import com.ctre.phoenix6.sim.TalonFXSimState;

import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.units.measure.*;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.simulation.ElevatorSim;
import edu.wpi.first.wpilibj.smartdashboard.Mechanism2d;
import edu.wpi.first.wpilibj.smartdashboard.MechanismLigament2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj2.command.button.Trigger;
import edu.wpi.first.math.filter.Debouncer;
import edu.wpi.first.math.filter.Debouncer.DebounceType;
import org.littletonrobotics.junction.Logger;

public class Elevator extends SubsystemBase {
    /** Position setpoints for the elevator. */
    public enum Setpoint {
        Top(Rotations.of(7)),
        Ground(Rotations.of(6));

        /** The position target of the setpoint in angular units. */
        public final Angle target;
        /** The position target of the setpoint in linear units. */
        public final Distance targetDist;

        private Setpoint(Angle target) {
            this.target = target;
            this.targetDist = kDrumRadius.times(target.in(Radians));
        }
        private Setpoint(Distance target) {
            this.target = Radians.of(target.div(kDrumRadius).magnitude());
            this.targetDist = target;
        }
    }

    private static final int kNumConfigAttempts = 2;

    /** Metres of carriage travel per mechanism rotation (drum circumference). */
    private static final double kMetersPerRot = 2.0 * Math.PI * 0.0191008;
    /** Speed cap requested 2026-09-20: ~0.75 m/s cruise, gentle accel. */
    private static final double kCruiseRps = 0.75 / kMetersPerRot;   // 6.25 rot/s
    private static final double kAccelRps2 = 3.0 / kMetersPerRot;    // 25 rot/s^2
    /** Target limits: never below the calibrated zero; max = Setpoint.Top (7 rot = 0.84 m) + 2 ft (raised 2026-09-20). */
    private static final double kJogMinRot = 0.0;
    private static final double kJogMaxRot = 7.0 + edu.wpi.first.math.util.Units.feetToMeters(2.0) / kMetersPerRot; // 12.08 rot = 1.45 m

    private static final double kGearRatio = 4;
    private static final Distance kDrumRadius = Meters.of(0.0191008);
    private static final Distance kMaxHeight = Meters.of(1.6); // sim + Mechanism2d only (reference had 0 -> degenerate sim)

    /* leader and follower motors */
    private final CANBus kCANBus = new CANBus("rio");
    private final TalonFX motor_id_50 = new TalonFX(50, kCANBus);
    private final TalonFX motor_id_61 = new TalonFX(61, kCANBus);

    /* device status signals */
    private final StatusSignal<Angle> motor_id_50Position = motor_id_50.getPosition(false);
    private final StatusSignal<AngularVelocity> motor_id_50Velocity = motor_id_50.getVelocity(false);
    private final StatusSignal<Current> motor_id_50TorqueCurrent = motor_id_50.getTorqueCurrent(false);

    /* controls used by the leader motors */
    private final MotionMagicVoltage setpointRequest = new MotionMagicVoltage(0);
    private final DutyCycleOut manualRequest = new DutyCycleOut(0);
    private final DutyCycleOut calibrationRequest = new DutyCycleOut(-0.1)
        .withIgnoreHardwareLimits(true)
        .withIgnoreSoftwareLimits(true);

    /** Trigger to detect when the elevator drives into a hard stop. */
    public final Trigger isHardStop = new Trigger(() ->
        motor_id_50Velocity.getValue().abs(RotationsPerSecond) < 1 &&
            motor_id_50TorqueCurrent.getValue().abs(Amps) > 10
    ).debounce(0.1);

    /* simulation */
    private final ElevatorSim elevatorSim_motor_id_50 = new ElevatorSim(
        DCMotor.getKrakenX60Foc(2),
        kGearRatio, 5, kDrumRadius.in(Meters),
        0.0, kMaxHeight.in(Meters), true, 0.0
    );

    private static final double kSimLoopPeriod = 0.002; // 2 ms
    private Notifier simNotifier = null;
    private double lastSimTime = 0.0;

    /* Mechanism2d visualization of the elevator */
    private final Mechanism2d mech2d = new Mechanism2d(1, kMaxHeight.in(Meters));
    private final MechanismLigament2d motor_id_50Mech2d = mech2d.getRoot("motor_id_50 Root", 0.500, 0)
        .append(new MechanismLigament2d("motor_id_50", elevatorSim_motor_id_50.getPositionMeters(), 90));

    /** Configs common across all motors. */
    private static final TalonFXConfiguration motorInitialConfigs = new TalonFXConfiguration();

    /** Configs common across just the leader motors. */
    private static final TalonFXConfiguration leaderInitialConfigs = motorInitialConfigs.clone();

    /** Configs for {@link #motor_id_50}. */
    private final TalonFXConfiguration motor_id_50Configs = leaderInitialConfigs.clone()
        .withMotorOutput(
            leaderInitialConfigs.MotorOutput.clone()
                .withNeutralMode(NeutralModeValue.Coast)
        )
        .withCurrentLimits(
            leaderInitialConfigs.CurrentLimits.clone()
                .withStatorCurrentLimit(Amps.of(120))
                .withStatorCurrentLimitEnable(true)
        )
        .withSlot0(
            leaderInitialConfigs.Slot0.clone()
                .withKP(16)
                .withKI(0)
                .withKD(0)
                .withKS(0.2)
                .withKV(0.48)
                .withKA(0)
                .withKG(0)
                .withGravityType(GravityTypeValue.Elevator_Static)
        )
        .withFeedback(
            leaderInitialConfigs.Feedback.clone()
                .withSensorToMechanismRatio(4)
        )
        .withHardwareLimitSwitch(
            leaderInitialConfigs.HardwareLimitSwitch.clone()
                .withForwardLimitEnable(true)
                .withForwardLimitAutosetPositionEnable(false)
                .withForwardLimitRemoteSensorID(0)
                .withForwardLimitSource(ForwardLimitSourceValue.LimitSwitchPin)
                .withForwardLimitType(ForwardLimitTypeValue.NormallyOpen)
                .withReverseLimitAutosetPositionEnable(false)
                .withReverseLimitEnable(true)
                .withReverseLimitRemoteSensorID(0)
                .withReverseLimitSource(ReverseLimitSourceValue.LimitSwitchPin)
                .withReverseLimitType(ReverseLimitTypeValue.NormallyOpen)
        )
        .withMotionMagic(
            leaderInitialConfigs.MotionMagic.clone()
                .withMotionMagicCruiseVelocity(RotationsPerSecond.of(kCruiseRps))   // 0.75 m/s (was 12 rps = 1.44 m/s)
                .withMotionMagicAcceleration(RotationsPerSecondPerSecond.of(kAccelRps2)) // 3 m/s^2 (was 80 rps^2)
        );

    /** Configs for {@link #motor_id_61}. */
    private final TalonFXConfiguration motor_id_61Configs = motorInitialConfigs.clone()
        .withMotorOutput(
            motorInitialConfigs.MotorOutput.clone()
                .withNeutralMode(NeutralModeValue.Coast)
        )
        .withCurrentLimits(
            motorInitialConfigs.CurrentLimits.clone()
                .withStatorCurrentLimit(Amps.of(120))
                .withStatorCurrentLimitEnable(true)
        )
        .withSlot0(
            motorInitialConfigs.Slot0.clone()
                .withKP(16)
                .withKI(0)
                .withKD(0)
                .withKS(0.2)
                .withKV(0.48)
                .withKA(0)
                .withKG(0)
                .withGravityType(GravityTypeValue.Elevator_Static)
        )
        .withFeedback(
            motorInitialConfigs.Feedback.clone()
                .withSensorToMechanismRatio(4)
        )
        .withHardwareLimitSwitch(
            motorInitialConfigs.HardwareLimitSwitch.clone()
                .withForwardLimitEnable(false)
                .withForwardLimitAutosetPositionEnable(false)
                .withForwardLimitRemoteSensorID(0)
                .withForwardLimitSource(ForwardLimitSourceValue.LimitSwitchPin)
                .withForwardLimitType(ForwardLimitTypeValue.NormallyOpen)
                .withReverseLimitAutosetPositionEnable(false)
                .withReverseLimitEnable(false)
                .withReverseLimitRemoteSensorID(0)
                .withReverseLimitSource(ReverseLimitSourceValue.LimitSwitchPin)
                .withReverseLimitType(ReverseLimitTypeValue.NormallyOpen)
        )
        .withMotionMagic(
            motorInitialConfigs.MotionMagic.clone()
                .withMotionMagicCruiseVelocity(RotationsPerSecond.of(20))
                .withMotionMagicAcceleration(RotationsPerSecondPerSecond.of(100))
        );

    public Elevator() {
        for (int i = 0; i < kNumConfigAttempts; ++i) {
            var status = motor_id_50.getConfigurator().apply(motor_id_50Configs);
            if (status.isOK()) break;
        }
        for (int i = 0; i < kNumConfigAttempts; ++i) {
            var status = motor_id_61.getConfigurator().apply(motor_id_61Configs);
            if (status.isOK()) break;
        }

        motor_id_61.setControl(
            new Follower(motor_id_50.getDeviceID(), MotorAlignmentValue.Opposed)
        );

        /* default command: hold the persistent target (needed for incremental X/Y jogging).
         * The generated default was manualDrive(0) (coast); holdTarget() keeps MotionMagic engaged instead. */
        setDefaultCommand(holdTarget());

        SmartDashboard.putData("Elevator", mech2d);

        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * @return The Position of the elevator
     */
    public Angle getPosition() {
        return motor_id_50Position.getValue();
    }

    /**
     * @return The Velocity of the elevator
     */
    public AngularVelocity getVelocity() {
        return motor_id_50Velocity.getValue();
    }

    /**
     * @return The TorqueCurrent of the elevator
     */
    public Current getTorqueCurrent() {
        return motor_id_50TorqueCurrent.getValue();
    }

    /**
     * Holds the elevator at the current position using PID.
     *
     * @return Command to run
     */
    public Command holdPosition() {
        return runOnce(() ->
            setpointRequest.withPosition(motor_id_50Position.getValue())
        ).andThen(run(() -> {
            motor_id_50.setControl(setpointRequest);
        }));
    }

    /* Persistent MotionMagic target in mechanism rotations; the default command holds it. */
    private double targetRotations = 0.0;

    /** Position-reached detection: within kTargetToleranceM of the target for kSettleSeconds. */
    private static final double kTargetToleranceM = 0.01;
    private static final double kSettleSeconds = 0.2;
    private boolean atTargetLatched = false;
    private Debouncer atTargetDebouncer = new Debouncer(kSettleSeconds, DebounceType.kRising);

    /** Carriage height above the calibrated zero (metres). */
    public Distance getHeight() {
        return Meters.of(motor_id_50Position.getValueAsDouble() * kMetersPerRot);
    }

    /** True once the carriage has been within tolerance of the current target for kSettleSeconds. */
    public boolean atTarget() {
        return atTargetLatched;
    }

    private void setTargetMeters(double meters) {
        targetRotations = Math.max(kJogMinRot, Math.min(kJogMaxRot, meters / kMetersPerRot));
        atTargetLatched = false; // reset the settle latch so a move issued from rest cannot finish instantly
        atTargetDebouncer = new Debouncer(kSettleSeconds, DebounceType.kRising);
    }

    /**
     * MotionMagic to {@code height} (clamped to [0, kJogMaxRot]) at the capped cruise speed; REQUIRES the
     * elevator (so a new move/sequence interrupts the previous one) and finishes once at the target for
     * kSettleSeconds. The default holdTarget() then keeps holding the same target.
     */
    public Command goTo(Distance height) {
        final double meters = height.in(Meters);
        return runOnce(() -> setTargetMeters(meters))
            .andThen(run(() -> motor_id_50.setControl(setpointRequest.withPosition(Rotations.of(targetRotations)))))
            .until(this::atTarget)
            .withName(String.format("ElevatorGoTo(%.3f m)", meters));
    }

    /** Current jog/hold target. */
    public Angle getTarget() {
        return Rotations.of(targetRotations);
    }

    /** Holds the persistent target with MotionMagic (default command). */
    public Command holdTarget() {
        return run(() -> motor_id_50.setControl(setpointRequest.withPosition(Rotations.of(targetRotations))))
            .withName("ElevatorHoldTarget");
    }

    /**
     * Moves the persistent target by {@code delta} (e.g. +/-1 inch), clamped to [kJogMinRot, kJogMaxRot].
     * The default command then drives there and holds. One press = one increment.
     */
    public Command jogBy(Distance delta) {
        final double deltaRot = delta.in(Meters) / kMetersPerRot;
        // No subsystem requirement: it only moves the target that holdTarget() (the default command) follows.
        return edu.wpi.first.wpilibj2.command.Commands.runOnce(() -> {
            setTargetMeters((targetRotations + deltaRot) * kMetersPerRot);
            System.out.printf("Elevator: target -> %.3f rot (%.3f m)%n", targetRotations, targetRotations * kMetersPerRot);
        }).withName("ElevatorJog");
    }

    /**
     * Continuous jog: while this command runs, the held target moves at {@code metersPerSecond} (clamped to the
     * limits); when it ends (button released) the target simply stops where it is and holdTarget() keeps it there.
     * No subsystem requirement (the default command does the driving).
     */
    public Command jogContinuous(double metersPerSecond) {
        return edu.wpi.first.wpilibj2.command.Commands.run(
                () -> setTargetMeters(targetRotations * kMetersPerRot + metersPerSecond * 0.02))
            .withName("ElevatorJogContinuous");
    }

    /**
     * Drives the elevator to the provided position setpoint.
     *
     * @param setpoint Function returning the setpoint to apply
     * @return Command to run
     */
    public Command goToSetpoint(Supplier<Setpoint> setpoint) {
        return run(() -> {
            setpointRequest.withPosition(setpoint.get().target);
            motor_id_50.setControl(setpointRequest);
        });
    }

    /**
     * Manually drives the elevator with the provided duty cycle output.
     *
     * @param manualOutput Function returning the duty cycle to apply
     * @return Command to run
     */
    public Command manualDrive(DoubleSupplier manualOutput) {
        return run(() -> {
            manualRequest.withOutput(manualOutput.getAsDouble());
            motor_id_50.setControl(manualRequest);
        });
    }

    /**
     * Recalibrates the elevator zero point. This slowly drives the elevator
     * down until we see a drop in velocity and a spike in stator current,
     * indicating that we've hit a hard stop.
     *
     * @return Command to run
     */
    public Command calibrateZero() {
        return run(() -> {
            motor_id_50.setControl(calibrationRequest);
        })
        .until(isHardStop)
        .andThen(
            manualDrive(() -> 0.0).withTimeout(0.25)
                .finallyDo(() -> {
                    motor_id_50.setPosition(Rotations.of(0));
                    motor_id_61.setPosition(Rotations.of(0));
                    targetRotations = 0.0; // hold at the freshly calibrated zero
                })
        );
    }

    @Override
    public void periodic() {
        /* refresh all status signals */
        BaseStatusSignal.refreshAll(
            motor_id_50Position,
            motor_id_50Velocity,
            motor_id_50TorqueCurrent
        );

        motor_id_50Mech2d.setLength(
            motor_id_50Position.getValueAsDouble() * kDrumRadius.in(Meters) * 2 * Math.PI
        );

        atTargetLatched = atTargetDebouncer.calculate(
            Math.abs(motor_id_50Position.getValueAsDouble() - targetRotations) * kMetersPerRot < kTargetToleranceM);

        /* AdvantageKit lite outputs (logging only) */
        Logger.recordOutput("Elevator/position_rot", motor_id_50Position.getValueAsDouble());
        Logger.recordOutput("Elevator/target_rot", targetRotations);
        Logger.recordOutput("Elevator/target_m", targetRotations * kMetersPerRot);
        Logger.recordOutput("Elevator/atTarget", atTargetLatched);
        Logger.recordOutput("Elevator/height_m", motor_id_50Position.getValueAsDouble() * kDrumRadius.in(Meters) * 2 * Math.PI);
        Logger.recordOutput("Elevator/velocity_rps", motor_id_50Velocity.getValueAsDouble());
        Logger.recordOutput("Elevator/torqueCurrent_a", motor_id_50TorqueCurrent.getValueAsDouble());
    }

    private void startSimThread() {
        motor_id_50.getSimState().Orientation = ChassisReference.CounterClockwise_Positive;
        motor_id_50.getSimState().setMotorType(TalonFXSimState.MotorType.KrakenX60);
        motor_id_61.getSimState().Orientation = ChassisReference.CounterClockwise_Positive;
        motor_id_61.getSimState().setMotorType(TalonFXSimState.MotorType.KrakenX60);

        lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        simNotifier = new Notifier(() -> {
            /* Calculate the time delta */
            final double currentTime = Utils.getCurrentTimeSeconds();
            final double deltaTime = currentTime - lastSimTime;
            lastSimTime = currentTime;

            final var motor_id_50Sim = motor_id_50.getSimState();
            final var motor_id_61Sim = motor_id_61.getSimState();

            /* First set the supply voltage of all the devices */
            motor_id_50Sim.setSupplyVoltage(RobotController.getBatteryVoltage());
            motor_id_61Sim.setSupplyVoltage(RobotController.getBatteryVoltage());

            /* Then calculate the new position and velocity of the simulated elevator */
            elevatorSim_motor_id_50.setInputVoltage(motor_id_50Sim.getMotorVoltage());
            elevatorSim_motor_id_50.update(deltaTime);

            /* Apply the new rotor position and velocity to the motors (before gear ratio) */
            motor_id_50Sim.setRawRotorPosition(
                Radians.of(elevatorSim_motor_id_50.getPositionMeters() / kDrumRadius.in(Meters) * kGearRatio)
            );
            motor_id_50Sim.setRotorVelocity(
                RadiansPerSecond.of(elevatorSim_motor_id_50.getVelocityMetersPerSecond() / kDrumRadius.in(Meters) * kGearRatio)
            );
            motor_id_61Sim.setRawRotorPosition(
                Radians.of(elevatorSim_motor_id_50.getPositionMeters() / kDrumRadius.in(Meters) * kGearRatio)
            );
            motor_id_61Sim.setRotorVelocity(
                RadiansPerSecond.of(elevatorSim_motor_id_50.getVelocityMetersPerSecond() / kDrumRadius.in(Meters) * kGearRatio)
            );
        });
        simNotifier.startPeriodic(kSimLoopPeriod);
    }
}